export const adminRole = "Admin";
export const userRole = "User";
export const InfinityTraderRole = "Infinity Trader";
export const paperTrader = "paperTrade";
export const infinityTrader = "Infinity Trader";
export const tenxTrader = "TenX Trader";
export const zerodhaAccountType = "ZERODHA";
export const xtsAccountType = "XTS";
export const internshipTrader = "Internship Trader";
